version: '3.8'

networks:
  cassandra-net:

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:

services:
  cassandra1:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra1
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cassandra1_data:/bitnami
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER = dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER = cassandra
      - CASSANDRA_PASSWORD=cassandrapassword
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra2:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra2
    ports:
      - 7001:7001
      - 9043:9043
    volumes:
      - cassandra2_data:/bitnami
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER = dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER = cassandra
      - CASSANDRA_PASSWORD=cassandrapassword
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra3:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra3
    ports:
      - 7002:7002
      - 9044:9044
    volumes:
      - cassandra3_data:/bitnami
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra3
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER = dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER = cassandra
      - CASSANDRA_PASSWORD=cassandrapassword
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M